group: "Gym"
name: "share/sac_hopper"

training:
  interface:
    type: "independent"
    population_size: -1
  config:
    update_interval: 1
    saving_interval: 10
    batch_size: 256
    optimizer: "Adam"
    actor_lr: 0.001
    critic_lr: 0.001
    sac_alpha: 0.2
    tau: 0.005  # soft update
    grad_norm_clipping: 5.0

rollout:
  type: "async"
  stopper: "simple_rollout"
  stopper_config:
    max_step: 1000
  fragment_length: 1000
  num_episodes: 8
  episode_seg: 1
  terminate: "any"
  callback: "simultaneous"

env_description:
  creator: "Gym"
  config:
    env_id: "Hopper-v2"

algorithms:
  SAC:
    name: "SAC"
    model_config:
      actor:
        network: mlp
        layers:
          - units: 256
            activation: ReLU
          - units: 256
            activation: ReLU
        output:
          type: "gaussian"
          activation: False
      critic:
        network: mlp
        layers:
          - units: 256
            activation: ReLU
          - units: 256
            activation: ReLU
        output:
          activation: False
    custom_config:
      action_squash: True

global_evaluator:
  name: "generic"

dataset_config:
  episode_capacity: 100000
  learning_start: 2000