group: "maatari/basketball"
name: "dqn_shared"

training:
  interface:
    type: independent
    population_size: -1
  config:
    update_interval: 5
    batch_size: 128

env_description:
  creator: "MAAtari"
  config:
    env_id: "basketball_pong_v2"
    # supersuit wrapper
    # see: https://github.com/PettingZoo-Team/SuperSuit
    scenario_configs:
      obs_type: "grayscale_image"
      num_players: 2
      wrappers:
        # resize_v0: downscale observation for faster processing
        # max_observation_v0: as per openai baseline's MaxAndSKip wrapper, maxes over the last {param} frames
        #   to deal with frame flickering
        # sticky_actions_v0: repeat_action_probability is set to {param} to introduce non-determinism to the system
        - name: "resize_v0"
          params:
            - 84
            - 84
        - name: "dtype_v0"
          params:
            - "float32"
        - name: "normalize_obs_v0"
          params:
            env_min: 0.
            env_max: 1.
      # must be either 2 or 4

algorithms:
  DQN:
    name: "DQN"
    custom_config:
      gamma: 0.98
      eps_max: 1.0
      eps_min: 0.1
      eps_anneal_time: 10000

rollout:
  type: "async"
  metric_type: "simple"
  fragment_length: 100
  # read rollout config to assign nested workers
  num_episodes: 200
  num_env_per_worker: 100
  terminate: "any"
  stopper: "simple_rollout"
  stopper_config:
    stop_num: 1000
  callback: "simultaneous"

global_evaluator:
  name: "generic"

dataset_config:
  episode_capacity: 300